version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: sentinel_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - sentinel-net

  postgres:
    image: postgres:15-alpine
    container_name: sentinel_postgres
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel123
      POSTGRES_DB: sentinelstream
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sentinel-net

  backend:
    build: .
    container_name: sentinel_backend
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://sentinel:sentinel123@postgres:5432/sentinelstream
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - sentinel-net

  frontend:
    build: ./frontend
    container_name: sentinel_frontend
    ports:
      - "3000:80"
    networks:
      - sentinel-net

volumes:
  redis_data:
  postgres_data:


networks:
  sentinel-net:
