"""Add category to transactions

Revision ID: 5a7763cc97bc
Revises: 8e7d15d60371
Create Date: 2026-02-03 14:32:10.534441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7763cc97bc'
down_revision: Union[str, Sequence[str], None] = '8e7d15d60371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'category')
    # ### end Alembic commands ###
